import {
  Activity,
  Bot,
  CheckCircle2,
  FileCode2,
  Globe2,
  MapPin,
  ShieldCheck,
  Terminal,
  Wand2,
  RotateCcw,
} from "lucide-react";
import { Eyebrow, Reveal, Section } from "./primitives";
import { CobeGlobe } from "./cobe-globe";

const LIVE_ACTIVITY = [
  {
    icon: Globe2,
    text: "bdata scrape completed",
    time: "2m ago",
    agent: "Bright Data CLI",
    statusColor: "text-brand",
    bgColor: "bg-brand/10",
  },
  {
    icon: RotateCcw,
    text: "Self-healed 2 broken selectors",
    time: "9m ago",
    agent: "bdata scraper heal",
    statusColor: "text-amber-500",
    bgColor: "bg-amber-500/10",
  },
  {
    icon: Wand2,
    text: "Gemini AI extracted 3 insights",
    time: "24m ago",
    agent: "gemini-2.5-flash",
    statusColor: "text-purple-500",
    bgColor: "bg-purple-500/10",
  },
  {
    icon: CheckCircle2,
    text: "Healed selectors approved",
    time: "1h ago",
    agent: "bdata scraper approve",
    statusColor: "text-success",
    bgColor: "bg-success/10",
  },
];

export function Console() {
  return (
    <Section id="console" className="py-16 md:py-24">
      <Reveal>
        <div className="max-w-2xl">
          <Eyebrow>Intelligence workspace</Eyebrow>            <h2 className="mt-5 text-[34px] font-extrabold leading-[1.08] tracking-tight text-ink sm:text-[46px]">
            Terminal-first scraping workflow.
          </h2>
          <p className="mt-5 text-[16px] leading-relaxed text-ink-soft">
            The entire pipeline runs from the CLI. Create scrapers, run them, heal broken selectors, 
            and approve fixes — all without leaving your terminal.
          </p>
        </div>
      </Reveal>

      <Reveal delay={120}>
        <div className="mt-12 grid gap-6 lg:grid-cols-2">
          {/* LEFT PANEL: Globe / Geo Network */}
          <div className="flex flex-col justify-between overflow-hidden rounded-[24px] border border-hairline bg-card shadow-lift">
            <div className="p-8 pb-0 flex-1 flex flex-col justify-center">
              <CobeGlobe />
            </div>
            
            <div className="border-t border-hairline bg-surface p-6 mt-4">
              <h3 className="flex items-center gap-2 text-[18px] font-bold text-ink">
                <Globe2 className="size-5 text-brand" />
                Bright Data Web Unlocker
              </h3>
              <p className="mt-2 text-[14px] leading-relaxed text-ink-soft">
                Route scraping traffic through Bright Data's proxy network. Bypass anti-bot protection and get clean, structured data from any public website.
              </p>
            </div>
          </div>

          {/* RIGHT PANELS */}
          <div className="grid gap-6">
            {/* TOP RIGHT: Skills / Scraper Config */}
            <div className="flex flex-col justify-between overflow-hidden rounded-[24px] border border-hairline bg-card shadow-lift">
              <div className="p-6">
                <div className="flex items-center gap-2 border-b border-hairline pb-3">
                  <span className="size-2.5 rounded-full bg-surface-2" />
                  <span className="size-2.5 rounded-full bg-surface-2" />
                  <span className="size-2.5 rounded-full bg-surface-2" />
                  <span className="ml-2 flex items-center gap-1.5 text-[12px] font-medium text-muted-foreground">
                    <FileCode2 className="size-3.5" /> books-scraper.yaml
                  </span>
                </div>
                <div className="mt-4 rounded-lg bg-surface-2 p-4 font-mono text-[11px] leading-[1.6]">
                  <div className="text-muted-foreground"># Scraper Configuration</div>
                  <div className="text-brand mt-2">collector_id:</div>
                  <div className="text-ink pl-4">c_mt4f331h17e4wjcvxk <span className="text-muted-foreground ml-2">// Generated by bdata scraper create</span></div>
                  <div className="text-brand mt-1">target:</div>
                  <div className="text-ink pl-4">https://books.toscrape.com</div>
                  <div className="text-brand mt-1">schedule:</div>
                  <div className="text-ink pl-4">daily_9am</div>
                  <div className="text-brand mt-1">self_healing:</div>
                  <div className="text-success pl-4">enabled</div>
                </div>
              </div>
              
              <div className="border-t border-hairline bg-surface p-6">
              <h3 className="flex items-center gap-2 text-[18px] font-bold text-ink">
                <Terminal className="size-5 text-brand" />
                Self-Healing via CLI
              </h3>
              <p className="mt-2 text-[14px] leading-relaxed text-ink-soft">
                Run <code className="text-brand bg-brand/10 px-1.5 py-0.5 rounded font-mono text-xs">bdata scraper heal</code> to auto-repair broken selectors. Approve or reject fixes with <code className="text-brand bg-brand/10 px-1.5 py-0.5 rounded font-mono text-xs">bdata scraper approve</code>.
              </p>
              </div>
            </div>

            {/* BOTTOM RIGHT: Live Activity */}
            <div className="flex flex-col justify-between overflow-hidden rounded-[24px] border border-hairline bg-card shadow-lift">
              <div className="p-6 space-y-3">
                {LIVE_ACTIVITY.map((activity, idx) => (
                  <div key={idx} className="flex items-center justify-between rounded-xl border border-hairline bg-surface p-3 transition-colors hover:bg-surface-2">
                    <div className="flex items-center gap-3">
                      <span className={`grid size-8 shrink-0 place-items-center rounded-lg ${activity.bgColor} ${activity.statusColor}`}>
                        <activity.icon className="size-4" />
                      </span>
                      <div className="min-w-0">
                        <p className="truncate text-[13px] font-semibold text-ink">{activity.text}</p>
                        <p className="flex items-center gap-1.5 text-[11px] text-muted-foreground mt-0.5">
                          <Bot className="size-3" /> {activity.agent}
                        </p>
                      </div>
                    </div>
                    <span className="text-[11px] font-medium text-muted-foreground whitespace-nowrap">{activity.time}</span>
                  </div>
                ))}
              </div>
              
              <div className="border-t border-hairline bg-surface p-6">
              <h3 className="flex items-center gap-2 text-[18px] font-bold text-ink">
                <Activity className="size-5 text-brand" />
                Live Activity Feed
              </h3>
              <p className="mt-2 text-[14px] leading-relaxed text-ink-soft">
                See every scrape, heal, and analysis your pipeline runs — all powered by the Bright Data CLI running in your terminal.
              </p>
              </div>
            </div>
          </div>
        </div>
      </Reveal>
    </Section>
  );
}
